es:
  host: 'localhost'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'

cache:
  address: 'localhost'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  suggestion_key_format: 'suggestion.%s'

db:
  host: 'localhost'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'municipality'

consumer:
  brokers: ['localhost:9092']
  topic: 'update.municipality.profilepicture'
  group_id: 'consumer.update.media.group'